USE master
GO

IF EXISTS(SELECT name FROM SYS.databases WHERE NAME = 'NORTHWIND_METADATA')
BEGIN
DROP DATABASE NORTHWIND_METADATA
END
GO

CREATE DATABASE NORTHWIND_METADATA
GO

USE NORTHWIND_METADATA
GO

CREATE TABLE ETLExecution(
	Id INT IDENTITY(1,1) NOT NULL,
	UserName NVARCHAR (50),
	MachineName NVARCHAR (50),
	PackageName NVARCHAR (50),
	ETLLoad DATETIME,
	ETLCountRows BIGINT,
	ETLCountNewRegister BIGINT,
	ETLCountModifiedRegister BIGINT
);
GO


